apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: ami-047bdb0f2722260c0  # AMD64 AMI
  - id: ami-0f8d526d53e47bc9f  # ARM64 AMI
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-karpenter-demo
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-karpenter-demo
  instanceProfile: KarpenterNodeInstanceProfile-eks-karpenter-demo