apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: ami-0a6793a25df710b06  # AMD64 AMI
  - id: ami-0ff3ffae254f9ede6  # ARM64 AMI
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-karpenter-demo
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-karpenter-demo

  instanceProfile: KarpenterNodeInstanceProfile-eks-karpenter-demo
