apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karpenter
  namespace: karpenter
subjects:
  - kind: ServiceAccount
    name: karpenter
    namespace: karpenter
roleRef:
  kind: Role
  name: karpenter
  apiGroup: rbac.authorization.k8s.io
