apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karpenter-leader-election
  namespace: karpenter
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karpenter-leader-election
  namespace: karpenter
subjects:
  - kind: ServiceAccount
    name: karpenter
    namespace: karpenter
roleRef:
  kind: Role
  name: karpenter-leader-election
  apiGroup: rbac.authorization.k8s.io
