apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: arm64
spec:
  amiFamily: AL2
  amiSelectorTerms:
  - id: ami-0f8d526d53e47bc9f  # The ARM64 AMI ID, need to be updated
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 50Gi
      volumeType: gp3
  instanceProfile: KarpenterNodeInstanceProfile-eks-karpenter-demo
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-karpenter-demo
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: eks-karpenter-demo
  tags:
    karpenter.sh/discovery: eks-karpenter-demo
  userData: |
    #!/bin/bash
    set -ex
    /etc/eks/bootstrap.sh eks-karpenter-demo --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup=karpenter,kubernetes.io/arch=arm64'

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: arm64
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmpty
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: arm64
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - t3.micro
        

        